apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api-deployment
  labels:
    app: sentiment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api
        image: 547355989093.dkr.ecr.us-east-1.amazonaws.com/sentiment-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
spec:
  type: LoadBalancer
  selector:
    app: sentiment-api
  ports:
  - port: 80
    targetPort: 5000
